-- MySQL Script generated by MySQL Workbench
-- 10/29/14 13:48:40
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Loja
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Loja` ;
CREATE SCHEMA IF NOT EXISTS `Loja` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Loja` ;

-- -----------------------------------------------------
-- Table `Loja`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loja`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Loja`.`Clientes` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `telefone` VARCHAR(80) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `Loja`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loja`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `Loja`.`Produtos` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `preco` DECIMAL(10,2) NULL,
  `estoque` INT NULL,
  `Produtoscol` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Loja`.`Vendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Loja`.`Vendas` ;

CREATE TABLE IF NOT EXISTS `Loja`.`Vendas` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NULL,
  `quantidade` INT NULL,
  `faturado` BIT NULL,
  `codigocliente` INT NULL,
  `codigoproduto` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `codigoCliente_idx` (`codigocliente` ASC),
  INDEX `codigoProduto_idx` (`codigoproduto` ASC),
  CONSTRAINT `codigoCliente`
    FOREIGN KEY (`codigocliente`)
    REFERENCES `Loja`.`Clientes` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigoProduto`
    FOREIGN KEY (`codigoproduto`)
    REFERENCES `Loja`.`Produtos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
